### ISSUE TITLE
IFC4 tesselated geometry is not converted

### ISSUE THREAD

**Issue by mathib** [pipauwel/IFCtoRDF#10]
While testing, it seemed that the IFC4 tesselated geometery is not converted into RDF.

See testfile from buildingSMART: https://github.com/buildingSMART/IfcDoc/blob/master/IfcKit/examples/basic-geometric-shape/tessellated-item.ifc

No triangles are added to inst:IfcTriangulatedFaceSet_18 and the inst:IfcCartesianPointList3D_8 doesn't contain any point coordinates, when the above IFC is converted into RDF (IfcOWL based) using the converter.

**Comment by pipauwel** [comment]
There was indeed a bug in the code. It should be corrected now. Can you run this again?

**Comment by mathib** [comment]
tested briefly and works now!
