### ISSUE TITLE
Support for IFC Alignment

### ISSUE THREAD

**Issue by jjkaelin** [pipauwel/IFCtoRDF#11]
Could you clarify the status of the IFCtoRDF conversion with regard to IFC Alignment? I understood Alignment to be part of IFC4x1 (e.g.  https://www.roadotl.eu/static/eurotl-ontologies/IFC4x1_Final_doc/index-en.html ). I tested IFCtoRDF-0.2 on IFC Alignment data and it it does not seem to convert Alignment data. If Alignment is not yet supported, do you have plans to support this in the near future? Thanks in advance for you response.

**Comment by jjkaelin** [comment]
Some additional clarifications:
1) After more review, I see that https://standards.buildingsmart.org/IFC/DEV/IFC4_1/OWL/
(in web page title shown as IFC4x1) does include support for IFC Alignments.
2) The file I am converting with IFCtoRDF has a header line: FILE_SCHEMA(('IFC4X1')).
3) I am attaching the test file used for the conversion. The output file includes no references to Alignment.
(To upload I needed to add a .txt extension.)
 
Am I misunderstanding something or is there a problem with the conversion?

[Test-100.ifc.txt](https://github.com/pipauwel/IFCtoRDF/files/3074716/Test-100.ifc.txt)

**Comment by lewismc** [comment]
I'll have a look at this @jjkaelin over the weekend.

**Comment by pipauwel** [comment]
Hi,

Apologies for a very late reply. This should be fixed with the latest commit: https://github.com/pipauwel/IFCtoRDF/pull/16. It would be great if you could try this with a sample file, @jjkaelin<https://github.com/jjkaelin>. Or maybe share an IfcAlignment file?

We'll include this in the 0.3 release.

Pieter




________________________________
Van: Lewis John McGibbney <notifications@github.com>
Verzonden: zaterdag 13 april 2019 0:48
Aan: pipauwel/IFCtoRDF
CC: Subscribed
Onderwerp: Re: [pipauwel/IFCtoRDF] Support for IFC Alignment (#11)


I'll have a look at this @jjkaelin<https://github.com/jjkaelin> over the weekend.

-

**Comment by jjkaelin** [comment]
Dear Pieter,

I would be happy to have a look at this and to send you some IFC alignment
files. I will try and get back to you this week.

Kind regards,
Joe Kaelin

**Comment by jjkaelin** [comment]
I built the 'issue11' branch and tested three IFC Alignment datafiles (see below, .txt appended to files in order 
[horizontal-alignment.rdf.txt](https://github.com/pipauwel/IFCtoRDF/files/3220192/horizontal-alignment.rdf.txt)
[civil3d_test_100m_stationing.rdf.txt](https://github.com/pipauwel/IFCtoRDF/files/3220193/civil3d_test_100m_stationing.rdf.txt)
[MainRoad_as_is_designed_1.1.rdf.txt](https://github.com/pipauwel/IFCtoRDF/files/3220194/MainRoad_as_is_designed_1.1.rdf.txt)
[horizontal-alignment.rdf.txt](https://github.com/pipauwel/IFCtoRDF/files/3220195/horizontal-alignment.rdf.txt)



to upload):
- all files appear to be successfully read and processed by IFCtoRDF-0.3-SNAPSHOT.jar
- no IFC Alignment features are however output 
- the only difference between the output files of the 'issue11' branch and the IFCtoRDF-0.2 release is with namespaces:
    diff MainRoad_as_is_designed_1.1.rdf   
       ../../IFCtoRDF-IFCtoRDF-0.2/target/MainRoad_as_is_designed_1.1.ttl 
   1,2c1,2
    < # baseURI: http://linkedbuildingdata.net/ifc/resources20190526_094206/
    < # imports: http://standards.buildingsmart.org/IFC/DEV/IFC4/ADD1/OWL
    ---
    > # baseURI: http://linkedbuildingdata.net/ifc/resources20190412_181310/
    > # imports: http://www.buildingsmart-tech.org/ifcOWL/IFC4_ADD1

The output file imports IFC ADD1 OWL. This seems to me strange, as the referenced FILE_SCHEMA is IFC4X1 (I tried changing the import file reference to IFC4x1 but see in the codebase that this is anyway read case-insensitive). Is this relevant?
  grep -i IFC4 horizontal-alignment.rdf
    # imports: http://standards.buildingsmart.org/IFC/DEV/IFC4/ADD1/OWL
  grep -i IFC4 horizontal-alignment.ifc
    FILE_DESCRIPTION(('IFC4X1'),'2;1');
    FILE_SCHEMA(('IFC4x1'));

The test datafiles that I use are:

horizontal-alignment.ifc
http://www.buildingsmart-tech.org/ifc/IFC4x1/final/html/annex/annex-e/horizontal-alignment.ifc

MainRoad_as_is_designed_1.1.ifc  
http://www.modelservers.org/public/V-Con/ReleaseP3/DataSets/SE/Alignment/

civil3d_test_100m_stationing.ifc
my own test 

Now that I have been through the build process, I can easily do more testing and am happy to do this. I am quite interested in exploring IFCtoRDF with alignment data.

**Comment by jjkaelin** [comment]
I built the 'issue11' branch and tested three IFC Alignment datafiles (see below at end):
- all files appear to be successfully read and processed by IFCtoRDF-0.3-SNAPSHOT.jar
- no IFC Alignment features are however output 
- the only difference between the output files of the 'issue11' branch and the IFCtoRDF-0.2 release is with namespaces:

>     diff MainRoad_as_is_designed_1.1.rdf  ../../IFCtoRDF-IFCtoRDF-0.2/target/MainRoad_as_is_designed_1.1.ttl 
   1,2c1,2
    < # baseURI: http://linkedbuildingdata.net/ifc/resources20190526_094206/
    < # imports: http://standards.buildingsmart.org/IFC/DEV/IFC4/ADD1/OWL
    ---
    > # baseURI: http://linkedbuildingdata.net/ifc/resources20190412_181310/
    > # imports: http://www.buildingsmart-tech.org/ifcOWL/IFC4_ADD1

The output file imports IFC ADD1 OWL. This seems to me strange, as the referenced FILE_SCHEMA is IFC4X1 (I tried changing the import file reference to IFC4x1 but see in the codebase that this is anyway read case-insensitive). Is this relevant?

>   grep -i IFC4 horizontal-alignment.rdf
    # imports: http://standards.buildingsmart.org/IFC/DEV/IFC4/ADD1/OWL
  grep -i IFC4 horizontal-alignment.ifc
    FILE_DESCRIPTION(('IFC4X1'),'2;1');
    FILE_SCHEMA(('IFC4x1'));

The test datafiles that I use are:

horizontal-alignment.ifc
http://www.buildingsmart-tech.org/ifc/IFC4x1/final/html/annex/annex-e/horizontal-alignment.ifc

MainRoad_as_is_designed_1.1.ifc  
http://www.modelservers.org/public/V-Con/ReleaseP3/DataSets/SE/Alignment/

civil3d_test_100m_stationing.ifc
my own test 

Now that I have been through the build process, I can easily do more testing and am happy to do this. I am quite interested in exploring IFCtoRDF with alignment data.

[horizontal-alignment.rdf.txt](https://github.com/pipauwel/IFCtoRDF/files/3220202/horizontal-alignment.rdf.txt)
[civil3d_test_100m_stationing.rdf.txt](https://github.com/pipauwel/IFCtoRDF/files/3220203/civil3d_test_100m_stationing.rdf.txt)
[MainRoad_as_is_designed_1.1.rdf.txt](https://github.com/pipauwel/IFCtoRDF/files/3220204/MainRoad_as_is_designed_1.1.rdf.txt)

**Comment by pipauwel** [comment]
Hi @jjkaelin,
I just tested this with the sample files. Indeed, the wrong ontology was selected for parsing the file. It should be fine now in the ISSUE-11 branch. Maybe you can double-check whether the output Alignment.ttl files are really complete?
Pieter
