### ISSUE TITLE
java.nio.file.FileSystemException: test_Barcelona_Pavilion.ttl

### ISSUE THREAD

**Issue by adumas21** [pipauwel/IFCtoRDF#12]
Hello,
When i try to compile your IFCtoRDF project with maven, i got this error :

INFO [main] (RDFWriter.java:1014) - *OK 3*: added property: expressIfcFaceOuterBound_262141 - orientation_IfcFaceBound - expressBOOLEAN_152251
 INFO [main] (IfcSpfReader.java:256) - Finished!!
java.nio.file.FileSystemException: test_Barcelona_Pavilion.ttl: Le processus ne peut pas accéder au fichier car ce fichier est utilisé par un autre processus.

java.nio.file.FileSystemException: test_Barcelona_Pavilion.ttl: Le processus ne peut pas accéder au fichier car ce fichier est utilisé par un autre processus.

java.nio.file.FileSystemException: test_Barcelona_Pavilion.ttl: Le processus ne peut pas accéder au fichier car ce fichier est utilisé par un autre processus.

Tests run: 3, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 142.708 sec <<< FAILURE!

Results :

Failed tests:   testConvertIFCFileToOutputTTL(be.ugent.TestIfcSpfReader)
  testShowFiles(be.ugent.TestIfcSpfReader): expected:<[Barcelona_Pavilion.ifc, Barcelona_Pavilion.ttl, 20160414office_model_CV2_fordesign.ifc, 20160414office_model_CV2_fordesign.ttl, ootest.txt]> but was:<[C:\a\IFCtoRDF-master\target\test-classes\showfiles\Barcelona_Pavilion.ifc, C:\a\IFCtoRDF-master\target\test-classes\showfiles\Barcelona_Pavilion.ttl, C:\a\IFCtoRDF-master\target\test-classes\showfiles\nested\20160414office_model_CV2_fordesign.ifc, C:\a\IFCtoRDF-master\target\test-classes\showfiles\nested\20160414office_model_CV2_fordesign.ttl, C:\a\IFCtoRDF-master\target\test-classes\showfiles\ootest.txt]>

Tests run: 3, Failures: 2, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 02:27 min
[INFO] Finished at: 2019-04-04T10:55:18+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12:test (default-test) on project IFCtoRDF: There are test failures.
[ERROR] 
[ERROR] Please refer to C:\a\IFCtoRDF-master\target\surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

Do you have an idea to solve this issue ? i tried with eclipe IDE and directly on batch with mvn.cmd
I use JDK 1.8.202 and maven 3.6.0
Thanks a lot for your help !

**Comment by pipauwel** [comment]
Dear sir,

Thank you for the notification. I have recently resolved some bugs, but I did not modify the tests. I will do so as soon as I can. In the meanwhile, you may be able to compile this code without the tests?

Pieter




________________________________
Van: adumas21 <notifications@github.com>
Verzonden: donderdag 4 april 2019 11:09
Aan: pipauwel/IFCtoRDF
CC: Subscribed
Onderwerp: [pipauwel/IFCtoRDF] java.nio.file.FileSystemException: test_Barcelona_Pavilion.ttl (#12)


Hello,
When i try to compile your IFCtoRDF project with maven, i got this error :

INFO [main] (RDFWriter.java:1014) - OK 3: added property: expressIfcFaceOuterBound_262141 - orientation_IfcFaceBound - expressBOOLEAN_152251
INFO [main] (IfcSpfReader.java:256) - Finished!!
java.nio.file.FileSystemException: test_Barcelona_Pavilion.ttl: Le processus ne peut pas accéder au fichier car ce fichier est utilisé par un autre processus.

java.nio.file.FileSystemException: test_Barcelona_Pavilion.ttl: Le processus ne peut pas accéder au fichier car ce fichier est utilisé par un autre processus.

java.nio.file.FileSystemException: test_Barcelona_Pavilion.ttl: Le processus ne peut pas accéder au fichier car ce fichier est utilisé par un autre processus.

Tests run: 3, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 142.708 sec <<< FAILURE!

Results :

Failed tests: testConvertIFCFileToOutputTTL(be.ugent.TestIfcSpfReader)
testShowFiles(be.ugent.TestIfcSpfReader): expected:<[Barcelona_Pavilion.ifc, Barcelona_Pavilion.ttl, 20160414office_model_CV2_fordesign.ifc, 20160414office_model_CV2_fordesign.ttl, ootest.txt]> but was:<[C:\a\IFCtoRDF-master\target\test-classes\showfiles\Barcelona_Pavilion.ifc, C:\a\IFCtoRDF-master\target\test-classes\showfiles\Barcelona_Pavilion.ttl, C:\a\IFCtoRDF-master\target\test-classes\showfiles\nested\20160414office_model_CV2_fordesign.ifc, C:\a\IFCtoRDF-master\target\test-classes\showfiles\nested\20160414office_model_CV2_fordesign.ttl, C:\a\IFCtoRDF-master\target\test-classes\showfiles\ootest.txt]>

Tests run: 3, Failures: 2, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 02:27 min
[INFO] Finished at: 2019-04-04T10:55:18+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12:test (default-test) on project IFCtoRDF: There are test failures.
[ERROR]
[ERROR] Please refer to C:\a\IFCtoRDF-master\target\surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

Do you have an idea to solve this issue ? i tried with eclipe IDE and directly on batch with mvn.cmd
I use JDK 1.8.202 and maven 3.6.0
Thanks a lot for your help !

-

**Comment by adumas21** [comment]
Hello,
Yeah the code compiled without the tests.
I used this link : https://github.com/pipauwel/IFCtoRDF/releases instead of https://github.com/pipauwel/IFCtoRDF/archive/master.zip to download the archive.
This happens with maven in batch and with eclipse.
On windows (7 & 10) and on Linux (centos 7.4).

**Comment by lewismc** [comment]
I can have a look here if it would help @pipauwel ?

**Comment by pipauwel** [comment]
Lewis,

That would be most helpful.

Actually, I have uploaded my own test files to the GIT repo (both input and result). It is likely better to use these files in the maven tests. Would you be able to use these files, instead, or in addition to the current sample file?

Pieter


--
prof. dr. ir.-arch. Pieter Pauwels
Department of Architecture and Urban Planning, Ghent University, Belgium
________________________________
Van: Lewis John McGibbney <notifications@github.com>
Verzonden: woensdag 10 april 2019 22:06
Aan: pipauwel/IFCtoRDF
CC: Pieter Pauwels; Mention
Onderwerp: Re: [pipauwel/IFCtoRDF] java.nio.file.FileSystemException: test_Barcelona_Pavilion.ttl (#12)


I can have a look here if it would help @pipauwel<https://github.com/pipauwel> ?

-

**Comment by lewismc** [comment]
@pipauwel please see pull request @adumas21 and test locally before merging.

I also went ahead and updated all of the Maven plugin dependencies.
