### ISSUE TITLE
The .ser files

### ISSUE THREAD

**Issue by jyrkioraskari** [pipauwel/IFCtoRDF#25]
I faced an interesting issue when using IFCtoRDF source under BIMserver code as Bot Plugin.  

This Maven statement in the BIMserver code 
<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>

Affects the reading of the .ser files.

I have a fix here:
jyrkioraskari/IFCtoLBD_BIMBot-Plugin

**Comment by pipauwel** [comment]
Thanks, I'll be looking forward to a pull request, or a more detailed suggestion. I am aware that there are better ways than reloading serialised objects from .ser files. It is very exciting to see that you found a solution.

**Comment by pipauwel** [comment]
Thanks for the issue and request. As the project is archived and no longer maintained, however, I can't implement this change any more.
