### ISSUE TITLE
Support for IFC4X2

### ISSUE THREAD

**Issue by jyrkioraskari** [pipauwel/IFCtoRDF#27]
It seems that IFCtoRDF does not support IFC4X2 yet.  We have a file that uses the format.

**Comment by lewismc** [comment]
Can you post the file here or stage it somewhere. Also, do you have a stacktrace to show?

**Comment by pipauwel** [comment]
The IFC4x2 schema has been withdrawn:
https://technical.buildingsmart.org/standards/ifc/ifc-schema-specifications/. Hence there was no need to support it. It is possible to support it by adding a number of files and enabling switches in the code.






-------- Oorspronkelijk bericht --------
Van: Lewis John McGibbney ***@***.***>
Datum: 27/05/2021 18:57 (GMT+01:00)
Aan: pipauwel/IFCtoRDF ***@***.***>
Cc: Subscribed ***@***.***>
Onderwerp: Re: [pipauwel/IFCtoRDF] Support for IFC4X2 (#27)


Can you post the file here or stage it somewhere. Also, do you have a stacktrace to show?

**Comment by jyrkioraskari** [comment]
> The IFC4x2 schema has been withdrawn: https://technical.buildingsmart.org/standards/ifc/ifc-schema-specifications/. Hence there was no need to support it. It is possible to support it by adding a number of files and enabling switches in the code.
> […](#)
Good to know it.  We have a file that uses it: 
ISO-10303-21;
HEADER;
FILE_DESCRIPTION(('ViewDefinition [CoordinationView]'),'2;1');
FILE_NAME('...,('Unknown Author','info@ifctoolsproject.com'),('Unknown Organization'),'IFC Tools Project - IFC Java Toolbox','IFC Java Toolbox','Unknown Authorizer');
FILE_SCHEMA(('IFC4X2'));
ENDSEC;

**Comment by pipauwel** [comment]
Thanks for the issue and request. As the project is archived and no longer maintained, however, I can't implement this change any more.
