### ISSUE TITLE
Tests fail

### ISSUE THREAD

**Issue by fkleedorfer** [pipauwel/IFCtoRDF#28]
To reprocduce:
1. clone the repository
2. run `mvn install`

**Comment by fkleedorfer** [comment]
The problem seems to be that the ontology URI has changed, but the tests have not been updated.

This is the output generated by the tests with #29 

``` 
org.opentest4j.AssertionFailedError: Actual output differs from expected output:
  input: file C:\DATA\DEV\workspace\IFCtoRDF\target\test-classes\convertIFCFileToOutputTTL\PiPauwel_IFCtoRDF_test10.ttl
  expected output file: target\PiPauwel_IFCtoRDF_test10.ttl
  difference at line 2
  expected line:# imports: http://standards.buildingsmart.org/IFC/DEV/IFC4/ADD1/OWL
    actual line:# imports: http://standards.buildingsmart.org/IFC/DEV/IFC4/ADD2_TC1/OWL
```

**Comment by fkleedorfer** [comment]
I tentatively replaced the occurrences of `http://standards.buildingsmart.org/IFC/DEV/IFC4/ADD1/OWL` in the `/src/test/resources/convertIFCFileToOutputTTL/.+.ttl` files to `http://standards.buildingsmart.org/IFC/DEV/IFC4/ADD2_TC1/OWL`. 

Next problem as per #29:
``` 
org.opentest4j.AssertionFailedError: Actual output differs from expected output:
  input: file C:\DATA\DEV\workspace\IFCtoRDF\target\test-classes\convertIFCFileToOutputTTL\PiPauwel_IFCtoRDF_test13.ttl
  expected output file: target\PiPauwel_IFCtoRDF_test13.ttl
  difference at line 4
  expected line:@prefix ifc:  <http://standards.buildingsmart.org/IFC/DEV/IFC4/ADD2_TC1/OWL#> .
    actual line:@base          <http://linkedbuildingdata.net/ifc/resources/> .
```
so, it seems that more about the ttl structure has changed. I don't think that the line-by line comparison of the models is the right way to go about this. It would be better to obtain a jena Model (or Dataset, if necessary) as the conversion result and from the expected file, and check if the models are isomorphic. I'll provide another PR that does that.

**Comment by pipauwel** [comment]
Thanks for the issue and request. As the project is archived and no longer maintained, however, I can't implement this change any more.
