### ISSUE TITLE
Optionally generate in-memory RDF graph

### ISSUE THREAD

**Issue by fkleedorfer** [pipauwel/IFCtoRDF#34]
Currently, IFCtoRDF only allows for parsing an IFC file and generating a TTL file.

For large IFC files, we use HDT to speed things up and use less memory. The process of first generating a TTL file which is then read using HDT takes more time than necessary. If we can generate an in-memory graph, we can write a HDT graph directly.

Also, an in-memory graph makes it a bit more straightforward to write unit tests.

I'll open a PR for this.

**Comment by Swissbite** [comment]
@pipauwel I think this issue has been solved by merging #35? At least we have an output stream in the current master branch. I resolved the test issues by #42

**Comment by pipauwel** [comment]
Thanks for the issue and request. As the project is archived and no longer maintained, however, I can't implement this change any more.
