### ISSUE TITLE
get Resource failed

### ISSUE THREAD

**Issue by c-mellueh** [pipauwel/IFCtoRDF#40]
Hi, 
I am Trying to transform an .ifc with
`java -jar .\IFCtoRDF-0.4-shaded.jar --dir ./`
and i'm getting this Error:
`ERROR [main] (RDFWriter.java:1028) - *ERROR 2*: getResource failed for http://linkedbuildingdata.net/ifc/resources20220922_112740/_32769`

**Comment by pipauwel** [comment]
Thanks for the issue and request. As the project is archived and no longer maintained, however, I can't implement this change any more.
