### ISSUE TITLE
IFC schemas need to be updated: currently using http instead of https

### ISSUE THREAD

**Issue by pbourreau** [pipauwel/IFCtoRDF#41]
The buildingSMART schemas moved from http to https. The files in resources need to be updated to generate TTL files with the correct prefix.
Alternatively, the files could be downloaded from a repositroy on the net (https://technical.buildingsmart.org/standards/ifc/ifc-schema-specifications/)?

**Comment by pipauwel** [comment]
yes, thanks for the suggestion. I might change it when the project becomes active again. Most of the IFC content is ideally managed inside buildingSMART.

**Comment by pipauwel** [comment]
Thanks for the issue and request. As the project is archived and no longer maintained, however, I can't implement this change any more.
