### ISSUE TITLE
Unclear code / Dead code

### ISSUE THREAD

**Issue by Swissbite** [pipauwel/IFCtoRDF#43]
@pipauwel

We need a lib to implement an IFC to RDF parser, and your lib seems to be one of the most used which is not AGPL licensed (thanks).

But by reading through the code, I found a quite strange piece of code, which - in my opinion - will not do what you intended:
https://github.com/pipauwel/IFCtoRDF/blob/2f3cdb8d9d1ffd00f872b201fb7e3bb5902b7357/src/main/java/be/ugent/IfcSpfParser.java#L99-L108

In prose, what I read by that piece of code (within the if branch):
1. L100: Push **current** with whatever it has onto the list stack ✔
2. L101: Create a temporary object list, initialize it empty ✔
3. L102 - L104: If there is something in the string builder, add it to **current**, clear the string builder ✔
4. L105: Add the temp empty list as an object on top of the builder ❓
5. L106: Set **current** to **temp** object list, which is **empty** 💣

If this is doing what you intended, then you could remove Line 101 - 105 and just clear the current... But I believe this is not what should be done here.

**Comment by vijayAthmanathan** [comment]
Java

**Comment by pipauwel** [comment]
Thanks for the issue and request. As the project is archived and no longer maintained, however, I can't implement this change any more.
