### ISSUE TITLE
PURL issue with 'http://purl.org/voc/express'

### ISSUE THREAD

**Issue by Philipp-p** [pipauwel/IFCtoRDF#44]
Your converter does attempt to read from 'http://purl.org/voc/express' which links to 'https://users.ugent.be/~pipauwel/ontologies/express/20150925/express.ttl'. This site is no longer active and leads to a '404 - Not Found'. I assume since you no longer work for them, they deactivated your personal site. However your personal website still offers the correct file under 'https://pi.pauwel.be/voc/express/20151211/express.ttl'. Therefore, the simplest fix for this issue would be to change the the PURL link to point to your personal website. I simply replaced the link for the time being in all files in resources as a workaround in the meantime. This of course is also a possible fix for this issue and I would have created a pull request, but I assume you used PURL for persistence reason und want to keep using it. Anyhow thanks for your work on this converter!

**Comment by pipauwel** [comment]
Thanks for the issue and request. As the project is archived and no longer maintained, however, I can't implement this change any more.
