### ISSUE TITLE
Register a DOI for this repository at Zenodo

### ISSUE THREAD

**Issue by GeorgFerdinandSchneider** [pipauwel/IFCtoRDF#9]
Dear Pieter,

if possible if would be great to register a DOI for this repository at Zenodo [GH Tutorial](https://guides.github.com/activities/citable-code/).

This allows to reference the repository in scientific publications.

Thanks!

Georg

**Comment by lewismc** [comment]
@GeorgFerdinandSchneider we should do it for our next release as well. @pipauwel I have some more code to contribute to #2 so I will try to submit that reasonably soon. This would allow use of IFC2RDF within Apache Any23.

**Comment by GeorgFerdinandSchneider** [comment]
Sure should be fine. The Zenodo DOIs are quite handy and more or less the APIs of both services do the job for you. if you need any help just msg me

**Comment by GeorgFerdinandSchneider** [comment]
@lewismc @pipauwel 

If there is anything I can help to register a DOI let me know.

**Comment by pipauwel** [comment]
Hi Georg,

I finally managed to look at this. Great suggestion! I registered the repository with Zenodo. We need to make a new release for this repository and then the DOI is there. I would like to check with @lewismc whether we can actually make such a new release. @lewismc?

Pieter


________________________________
Van: Georg Ferdinand Schneider <notifications@github.com>
Verzonden: dinsdag 19 juni 2018 15:44
Aan: pipauwel/IFCtoRDF
CC: Pieter Pauwels; Mention
Onderwerp: Re: [pipauwel/IFCtoRDF] Register a DOI for this repository at Zenodo (#9)


@lewismc<https://github.com/lewismc> @pipauwel<https://github.com/pipauwel>

If there is anything I can help to register a DOI let me know.

-

**Comment by lewismc** [comment]
Hi @pipauwel yes I think you should roll a release with the new code. Call it 0.3. Let me know when you want to do this.

**Comment by pipauwel** [comment]
?Hi Lewis,

Issues 11 and 14 should be resolved. Can you check? If okay, we can do that 0.3 release.

Pieter



________________________________
Van: Lewis John McGibbney <notifications@github.com>
Verzonden: donderdag 11 april 2019 23:15
Aan: pipauwel/IFCtoRDF
CC: Pieter Pauwels; Mention
Onderwerp: Re: [pipauwel/IFCtoRDF] Register a DOI for this repository at Zenodo (#9)


Hi @pipauwel<https://github.com/pipauwel> yes I think you should roll a release with the new code. Call it 0.3. Let me know when you want to do this.

-

**Comment by pipauwel** [comment]
making new release of the software - Zenodo DOI integration should be included.

**Comment by lewismc** [comment]
Nice
